// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"go-zero-chat/ent/group"
	"go-zero-chat/ent/grouprelation"
	"go-zero-chat/ent/user"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
)

// GroupRelation is the model entity for the GroupRelation schema.
type GroupRelation struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 创建时间
	CreatedAt time.Time `json:"created_at,omitempty"`
	// 更新时间
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// 删除时间
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// 群id
	GroupID int `json:"group_id,omitempty"`
	// 群成员id
	UserID int `json:"user_id,omitempty"`
	// 对应的类型 1普通成员 2管理员
	Type int `json:"type,omitempty"`
	// 描述相关
	Desc string `json:"desc,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the GroupRelationQuery when eager-loading is set.
	Edges        GroupRelationEdges `json:"edges"`
	selectValues sql.SelectValues
}

// GroupRelationEdges holds the relations/edges for other nodes in the graph.
type GroupRelationEdges struct {
	// Group holds the value of the group edge.
	Group *Group `json:"group,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// GroupOrErr returns the Group value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupRelationEdges) GroupOrErr() (*Group, error) {
	if e.loadedTypes[0] {
		if e.Group == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: group.Label}
		}
		return e.Group, nil
	}
	return nil, &NotLoadedError{edge: "group"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e GroupRelationEdges) UserOrErr() (*User, error) {
	if e.loadedTypes[1] {
		if e.User == nil {
			// Edge was loaded but was not found.
			return nil, &NotFoundError{label: user.Label}
		}
		return e.User, nil
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*GroupRelation) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case grouprelation.FieldID, grouprelation.FieldGroupID, grouprelation.FieldUserID, grouprelation.FieldType:
			values[i] = new(sql.NullInt64)
		case grouprelation.FieldDesc:
			values[i] = new(sql.NullString)
		case grouprelation.FieldCreatedAt, grouprelation.FieldUpdatedAt, grouprelation.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the GroupRelation fields.
func (gr *GroupRelation) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case grouprelation.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			gr.ID = int(value.Int64)
		case grouprelation.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				gr.CreatedAt = value.Time
			}
		case grouprelation.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				gr.UpdatedAt = value.Time
			}
		case grouprelation.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				gr.DeletedAt = new(time.Time)
				*gr.DeletedAt = value.Time
			}
		case grouprelation.FieldGroupID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field group_id", values[i])
			} else if value.Valid {
				gr.GroupID = int(value.Int64)
			}
		case grouprelation.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				gr.UserID = int(value.Int64)
			}
		case grouprelation.FieldType:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field type", values[i])
			} else if value.Valid {
				gr.Type = int(value.Int64)
			}
		case grouprelation.FieldDesc:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field desc", values[i])
			} else if value.Valid {
				gr.Desc = value.String
			}
		default:
			gr.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the GroupRelation.
// This includes values selected through modifiers, order, etc.
func (gr *GroupRelation) Value(name string) (ent.Value, error) {
	return gr.selectValues.Get(name)
}

// QueryGroup queries the "group" edge of the GroupRelation entity.
func (gr *GroupRelation) QueryGroup() *GroupQuery {
	return NewGroupRelationClient(gr.config).QueryGroup(gr)
}

// QueryUser queries the "user" edge of the GroupRelation entity.
func (gr *GroupRelation) QueryUser() *UserQuery {
	return NewGroupRelationClient(gr.config).QueryUser(gr)
}

// Update returns a builder for updating this GroupRelation.
// Note that you need to call GroupRelation.Unwrap() before calling this method if this GroupRelation
// was returned from a transaction, and the transaction was committed or rolled back.
func (gr *GroupRelation) Update() *GroupRelationUpdateOne {
	return NewGroupRelationClient(gr.config).UpdateOne(gr)
}

// Unwrap unwraps the GroupRelation entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (gr *GroupRelation) Unwrap() *GroupRelation {
	_tx, ok := gr.config.driver.(*txDriver)
	if !ok {
		panic("ent: GroupRelation is not a transactional entity")
	}
	gr.config.driver = _tx.drv
	return gr
}

// String implements the fmt.Stringer.
func (gr *GroupRelation) String() string {
	var builder strings.Builder
	builder.WriteString("GroupRelation(")
	builder.WriteString(fmt.Sprintf("id=%v, ", gr.ID))
	builder.WriteString("created_at=")
	builder.WriteString(gr.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(gr.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := gr.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("group_id=")
	builder.WriteString(fmt.Sprintf("%v", gr.GroupID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", gr.UserID))
	builder.WriteString(", ")
	builder.WriteString("type=")
	builder.WriteString(fmt.Sprintf("%v", gr.Type))
	builder.WriteString(", ")
	builder.WriteString("desc=")
	builder.WriteString(gr.Desc)
	builder.WriteByte(')')
	return builder.String()
}

// GroupRelations is a parsable slice of GroupRelation.
type GroupRelations []*GroupRelation
