// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"go-zero-chat/ent/grouprelation"
	"go-zero-chat/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// GroupRelationDelete is the builder for deleting a GroupRelation entity.
type GroupRelationDelete struct {
	config
	hooks    []Hook
	mutation *GroupRelationMutation
}

// Where appends a list predicates to the GroupRelationDelete builder.
func (grd *GroupRelationDelete) Where(ps ...predicate.GroupRelation) *GroupRelationDelete {
	grd.mutation.Where(ps...)
	return grd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (grd *GroupRelationDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, grd.sqlExec, grd.mutation, grd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (grd *GroupRelationDelete) ExecX(ctx context.Context) int {
	n, err := grd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (grd *GroupRelationDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(grouprelation.Table, sqlgraph.NewFieldSpec(grouprelation.FieldID, field.TypeInt))
	if ps := grd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, grd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	grd.mutation.done = true
	return affected, err
}

// GroupRelationDeleteOne is the builder for deleting a single GroupRelation entity.
type GroupRelationDeleteOne struct {
	grd *GroupRelationDelete
}

// Where appends a list predicates to the GroupRelationDelete builder.
func (grdo *GroupRelationDeleteOne) Where(ps ...predicate.GroupRelation) *GroupRelationDeleteOne {
	grdo.grd.mutation.Where(ps...)
	return grdo
}

// Exec executes the deletion query.
func (grdo *GroupRelationDeleteOne) Exec(ctx context.Context) error {
	n, err := grdo.grd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{grouprelation.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (grdo *GroupRelationDeleteOne) ExecX(ctx context.Context) {
	if err := grdo.Exec(ctx); err != nil {
		panic(err)
	}
}
