// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Contact is the predicate function for contact builders.
type Contact func(*sql.Selector)

// File is the predicate function for file builders.
type File func(*sql.Selector)

// Group is the predicate function for group builders.
type Group func(*sql.Selector)

// GroupMsg is the predicate function for groupmsg builders.
type GroupMsg func(*sql.Selector)

// GroupRelation is the predicate function for grouprelation builders.
type GroupRelation func(*sql.Selector)

// Message is the predicate function for message builders.
type Message func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
